server:
  port: 8085

spring:
  main:
    banner-mode: off
  data:
    mongodb:
      username: "supersecret"
      password: "super-secret-password"
      database: orders
      authentication-database: "admin"
      host: "localhost"
      port: 27017
  application:
    name: classic-service
